### ISSUE TITLE
GH Actions now requires code to run on Node v16

### ISSUE THREAD

**Issue by co510** [katalon-studio/katalon-studio-github-action#23]
Github is migrating the requirements for all Actions to run on Node v16.  Please update the GH Action for Katalon Studio accordingly so that users can continue running KRE through a Github runner.

![Node_errorMsg](https://user-images.githubusercontent.com/69608542/196250532-f9ae88ea-1ef2-416d-95f2-558c4940886a.JPG)

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by thvu-katalon** [comment]
This is obsoleted.
